int a = 440;
int b = 494;
int c = 262;
int d = 294;
int e = 330;
int f = 349;
int g = 392;
int wholeNote = 3500;
Console.Beep(b + 290,wholeNote * 3/4 + 1);
Console.Beep(g + 303 ,wholeNote);
Console.Beep(e + 257 ,wholeNote/4);
Console.Beep(g + 303 ,wholeNote/4);
Console.Beep(c + 402 ,wholeNote);
Console.Beep(e + 193 ,wholeNote/4);
Console.Beep(f + 283 ,wholeNote/4);
Console.Beep(a + 83, wholeNote/4);
Console.Beep(d + 365 ,wholeNote/4);
Console.Beep(e + 193 ,wholeNote/2);
Console.Beep(b,wholeNote/2);
Console.Beep(e + 193 ,wholeNote/4);
Console.Beep(b,wholeNote * 3/4 + 1);
Console.Beep(a,wholeNote/4);
Console.Beep(d + 293 ,wholeNote/4);
Console.Beep(a,wholeNote/4);
Console.Beep(g,wholeNote/4);
Console.Beep(a,wholeNote/4);
Console.Beep(g,wholeNote/2);
Console.Beep(f,wholeNote/4);
Console.Beep(g,wholeNote/4);
Console.Beep(f,wholeNote * 3/4 + 1);
Console.Beep(e,wholeNote);
Console.Beep(e,wholeNote/4);
Console.Beep(f,wholeNote/4);
Console.Beep(e,wholeNote/4);
Console.Beep(a,wholeNote/4);
Console.Beep(e,wholeNote/4);
Console.Beep(d,wholeNote/4);
Console.Beep(e,wholeNote/4);
Console.Beep(d,wholeNote * 3/4 + 1);
Console.Beep(c,wholeNote/4);
Console.Beep(d,wholeNote/4);
Console.Beep(c,wholeNote * 3/4 + 1);
Console.Beep(c - 15 ,wholeNote);
//Console.Beep(g,wholeNote);
// Console.Beep(a,wholeNote);
//Console.Beep(c,wholeNote);
//Console.Beep(f,wholeNote);
//Console.Beep(g,wholeNote);
//Console.Beep(f,wholeNote);
//Console.Beep(a,wholeNote);
//Console.Beep(b, wholeNote);
// Console.Beep(f, wholeNote);
// Console.Beep(a,wholeNote); 
// Console.Beep(c,wholeNote);
// Console.Beep(e, wholeNote);
// Console.Beep(f, wholeNote);
// Console.Beep(e, wholeNote);
// Console.Beep(a, wholeNote);
// Console.Beep(e, wholeNote);
// Console.Beep(d, wholeNote);
// Console.Beep(f, wholeNote);
// Console.Beep(a, wholeNote);
// Console.Beep(d, wholeNote);
// Console.Beep(e, wholeNote);
// Console.Beep(d, wholeNote);
// Console.Beep(f, wholeNote);
// Console.Beep(g, wholeNote);
// Console.Beep(c, wholeNote);
// Console.Beep(d, wholeNote);
// Console.Beep(c,wholeNote);
// Console.Beep(d, wholeNote);
// Console.Beep(g, wholeNote);
// Console.Beep(c, wholeNote);
// Console.Beep(g, wholeNote);
// Console.Beep(g, wholeNote);
// Console.Beep(b, wholeNote);
// Console.Beep(g, wholeNote); //
